CREATE DATABASE IF NOT EXISTS PHOTO;
USE PHOTO;
SHOW DATABASES;
CREATE TABLE IF NOT EXISTS USERTB(uid INT NOT NULL AUTO_INCREMENT, email VARCHAR(255) NOT NULL UNIQUE, username VARCHAR(255) NOT NULL,password VARCHAR(255) NOT NULL,PRIMARY KEY(uid));
CREATE TABLE IF NOT EXISTS CLLECTB(cid INT NOT NULL AUTO_INCREMENT, pub TINYINT(1) NOT NULL,PRIMARY KEY(cid));
CREATE TABLE IF NOT EXISTS ImageTB(pid INT NOT NULL AUTO_INCREMENT, uri VARCHAR(255), upload_date DATE, description VARCHAR(255), uid INT NOT NULL, orig_uid INT NOT NULL, PRIMARY KEY(pid));
CREATE TABLE IF NOT EXISTS ACL(cid INT NOT NULL, uid INT NOT NULL, role INT NOT NULL, PRIMARY KEY(cid, uid));
CREATE TABLE IF NOT EXISTS ICJ(pid INT NOT NULL, cid INT NOT NULL, PRIMARY KEY(pid, cid));
