FROM openjdk:15-jdk-alpine as medium
WORKDIR /app
COPY ./.aws/ /.aws
COPY ./server/pom.xml .
COPY ./server/mvnw .
COPY ./server/.mvn .mvn
RUN ./mvnw dependency:go-offline -B
COPY ./server/src ./src
RUN ./mvnw package -DskipTests

FROM openjdk:15-jdk-alpine
WORKDIR /app

COPY --from=medium /app/target/photocol-server-*.jar ./server.jar
ENTRYPOINT ["java","-jar","server.jar"]
