FROM node:alpine as build
WORKDIR /app
COPY ./website/package.json ./
COPY ./website/package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY ./website ./
RUN npm run build

FROM nginx:mainline
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
