version: "3.8"
services:
    adminer:
        image: adminer
        container_name: cont_manage
        restart: always
        ports: 
            - "8080:8080"
        networks:
            - front
            - back
        
    db:
        image: mariadb:latest
        container_name: photocol_DB
        restart: always
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: photocol
        volumes:
            - ./script:/docker-entrypoint-initdb.d
            - ./data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
        expose:
            - "3306"
        ports:
            - "6600:3306"
        networks:
            - back
            
    backup:
        build: ./backup
        container_name: photocol-backup
        restart: always
        volumes: 
            - /etc/localtime:/etc/localtime:ro
            - ./backup/data:/backup
            - ./backup/backup.sh:/etc/periodic/daily/backup.sh
        environment:
            MYSQL_CONTAINER_NAME: photocol_DB
            MYSQL_DATABASE: photocol
            MYSQL_USER: photo_server
            MYSQL_PASSWORD: password
        depends_on:
            - db
        networks:
            - back
        command: crond -f -d 8
        
    server:
        build:
            context: ./
            dockerfile: Dockerfile.server
        container_name: backend
        environment:
            DB_URL: "jdbc:mysql://db/"
        restart: always
        ports:
            - "6700:4567"
        links: 
            - "db:database"
        depends_on:
            - db
        networks:
            - back
            - front

            
    webclient:
        build:
            context: ./
            dockerfile: Dockerfile.web
        container_name: frontend
        volumes: 
            - ./logs/client/:/var/log/nginx/
            - /etc/localtime:/etc/localtime:ro
        restart: always
        ports:
            - "1111:80"
        depends_on:
            - server
        networks:
            - front
        
networks:
    front:
    back:
    
