FROM openjdk:8-jdk-alpine as medium
WORKDIR /app
COPY ./server/pom.xml .
COPY ./server/mvnw .
COPY ./server/.mvn .mvn
RUN ./mvnw dependency:go-offline -B
COPY ./server/src ./src
RUN ./mvnw package -DskipTests

FROM openjdk:8-jre-alpine
WORKDIR /app

COPY --from=medium /app/target/photocol-server-*.jar ./server.jar
EXPOSE 4567
ENTRYPOINT ["java","-jar","server.jar"]
