#!/bin/bash

# prints the input
function setup() {
    rm -rf website server
    git clone -b dbv2 https://github.com/photocol/photocol-server.git server
    git clone -b dbv2 https://github.com/photocol/photocol-website.git website
    mvn -N io.takari:maven:wrapper -f ./server
    if [ $1 = "lo" ]
        then
            cp -f ./.env.production ./website/.env.production
    fi
}

function push() {
    git add .
    git commit -m "auto"
    git push origin $1
}
